### PR TITLE
Fix navigation links - replace anchor links with NavLinks

### LINKED ISSUE #3: 3. As a user, I want to be able to navigate to all the pages in the application by clicking the links in the nav bar
## Summary

Users need to be able to navigate between the pages of our application in order to access all of its features. There is a navigation bar in the `Layout.jsx` component, but it's not quite feature-complete: the links in the nav element don't actually allow the user to navigate from page to page.

## Acceptance criteria
- [x] The `nav` element is added to the `Layout` component
- [x] Links to the "Home", "List", and "Add item" pages of the app are In the `nav` element
- [x] The links all function as expected using  the `NavLink` component from `react-router-dom`

## Notes
- The [official docs for the `NavLink` component](https://reactrouter.com/en/6.14.2/components/nav-link) will come in very handy!
- While a standard anchor element (`<a>`) _could_ allow a user to navigate from page to page, the `NavLink` component adds additional behavior that is essential to our app functioning correctly!

### PR DESCRIPTION
**Pull request by rachelspencer**
## Description

Added functional NavLinks to navigate between routes/pages. 

## Related Issue

Closes #3

## Acceptance Criteria

 - [x] The nav element is added to the Layout component
 - [x] Links to the "Home", "List", and "Add item" pages of the app are In the nav element
 - [x] The links all function as expected using the NavLink component from react-router-dom

## Type of Changes

Enhancement, Accessibility

### Before
NavLinks not working

### After
Home NavLink Working

List NavLink Working

ManageList NavLink Working

## Testing Steps / QA Criteria

- `git pull`
- `npm ci`
- `git switch -b ja-rs-feature-fix-navlinks`
- `npm run start`
- click between all links to ensure navigation functionality is working

### CODE REVIEW

**Comment by rachelspencer** [comment]
Hey @sillytsundere  and @trushmi,
Jose and I updated the Layout.jsx page to make the navlinks work.
Thank for the review.
JA & RS

**Review by sillytsundere — APPROVED** [review]
Works great!

**Review by trushmi — APPROVED** [review]
LGTM!

**Review by polly89 — APPROVED** [review]
I pulled down the branch and tested the links. Great job meeting the acceptance criteria!

**Comment by rachelspencer** [comment]
Thanks team!

**Pull request merged**
