### PR TITLE
Create purchase urgency badges

### PR DESCRIPTION
**Pull request by rachelspencer**
## Description

Color coded urgency badges have been created to assist the user in understanding how soon they need to buy an item. The badges are displayed on the `List` page for each item.

## Related Issue

Closes #23 

## Acceptance Criteria

- [x] The `List` component renders color coded badges that displays the purchase urgency for an item
- [x] The badges are accessible

## Type of Changes
refactoring

### Before
Text renders the purchase urgency
Screenshot 2024-03-29 at 4 39 36 PM

### After
Text and color coded badge renders the purchase urgency
Screenshot 2024-03-29 at 5 09 26 PM
Screenshot 2024-03-29 at 5 10 50 PM

## Testing Steps / QA Criteria
- git pull
- git checkout rs-style-purchase-priority-badges
- npm ci
- npm start
- Click on the `Coffee Supply` list name on the `Home` page
- Navigate to the `List` page
- Notice the color badges for overdue, soon, kind of soon, not so soon, and inactive
- Browse other lists and see these badges there as well. You may need to manipulate data in FireStore to see all of the badge colors.

Note: Styling of how the badge interacts with other items on this page will be handled when the `List` page is styled.

### CODE REVIEW

**Review by jaguilar89 — APPROVED** [review]
Looks good! 🫡

**Comment by rachelspencer** [comment]
Thanks @jaguilar89!

**Review by sillytsundere — APPROVED** [review]
Looks good to me! Approved!

**Comment by rachelspencer** [comment]
Thank you @sillytsundere!

**Review by trushmi — APPROVED** [review]
Looks good to me! Great work @rachelspencer tackling this issue !

**Comment by rachelspencer** [comment]
Thank you @trushmi!

**Review by polly89 — APPROVED** [review]
Great job making these tags beautiful and accessible. I only have one non-blocking comment, and it can be dealt with on this ticket or when you go to do media queries. 

As you can see in this screenshot, it gets a bit crowded when you are in mobile view. Perhaps consider placing the media tag under the item name when you are in mobile view. 

Screenshot 2024-04-01 at 3 17 14 PM

**Comment by rachelspencer** [comment]
Thanks @polly89! I am going to tackle the styling issue now when I style the whole List component.

Thanks again!

**Pull request merged**
