### PR TITLE
Create validation message that prompts a user to sign in if they want to use the app.

### LINKED ISSUE #32: 15. Create validation messages that prompts a user to sign in if they want to use the app.
Create validation messages that prompts a user to sign in if they want to use the app. But implement it so that the user can still browse the whole app without logging in. Ask mentors for their opinion for best practices.

## Summary
When a user views the app, they should be prompted to sign in (using their Google account) if they want to interact with the features of the app. However, a user should still be able to navigate each route.

## Acceptance Criteria
- [x] The app should display a prompt on each page that instructs the user to sign in if they want to view that page (e.g. "To create a list/view a list/manage a list, please sign in.").
  - Alternatively, consider automatically redirecting the user to a login page when they try to access a page they are not authorized to view.
- [x] When a user is signed in, they should be able to view all pages and interact with the app's features (creating lists, viewing lists, adding new items to lists).

## Notes
- Consider how you want to handle user flow when the user is not signed in. You can display a prompt to the user instructing them to sign in before viewing a page, or you can redirect them to a login page. There are pros and cons for each:

|  | Prompt On Each Page | Redirect to Sign-In Page |
| :------------: | :------------: | :------------: |
| **Pros** | Provides context for the need to sign-in (relevant to the current page).  | Streamlines the process, user gets to sign-in page faster.  |
| **Cons**  | Can be repetitive for users. <br /> Breaks navigation flow, requiring an extra step each time.   | Being automatically redirected may feel disruptive to the user.  |

- Right now, the user gets no feedback when signing in or out. Consider rendering some form of feedback for users that are signed in (e.g. Confirm sign-in and/or display their name in the header). Do the same for sign-outs.

### PR DESCRIPTION
**Pull request by jaguilar89**
## Description

This code adds a prompt that pops up for the user whenever they try to perform an action(e.g. create a list) when not signed into the app.

Also.. I know I was not tasked with styling buttons, but some color styling for the prompt buttons, as well as the `create a list` and `submit` buttons was added, by experimenting with the method I outlined in the issue doc (also outlined [here](https://www.frontend.fyi/v/fixing-radix-themes-with-css-cascade-layers)). This can be removed before merging if needed.

## Related Issue

Closes #32 

## Acceptance Criteria
- [x] The app should display a prompt on each page that instructs the user to sign in if they want to view that page (e.g. "To create a list/view a list/manage a list, please sign in.").
  - Alternatively, consider automatically redirecting the user to a login page when they try to access a page they are not authorized to view.
- [x] When a user is signed in, they should be able to view all pages and interact with the app's features (creating lists, viewing lists, adding new items to lists).

## Type of Changes

Enhancement

### Before
**User not signed in. No prompt when clicking on create list.**
image

### After
**User not signed in. Sign in prompt appears when user attempts to create a list.**
image

## Testing Steps / QA Criteria

`git pull`
`git checkout ja-feature-signin-prompt`
`npm ci`
`npm start`

- If signed into the app, sign out.
- On the home page, try to create a list. Upon clicking `create a list` there should be a prompt for you to sign in.
  - Clicking `Sign In` should redirect you to your Google sign in page, where you can log in successfully.
- Navigate to the `Manage List` page and try to add an item. Upon clicking `Submit` there should be a prompt for you to sign in.

### CODE REVIEW

**Review by rachelspencer — APPROVED** [review]
Hey Jose! This looks nice! 

I don't mind about some of the buttons being styled as a result of your experimentation. Is there a way to make the buttons the same color when the user is or isn't signed in? Right now its alternating between the light and dark blue.

Could we also add this sign in prompt to the share an email feature on the `Manage List` page. What do you think?

**Comment by jaguilar89** [comment]
> Hey Jose! This looks nice!
> 
> I don't mind about some of the buttons being styled as a result of your experimentation. Is there a way to make the buttons the same color when the user is or isn't signed in? Right now its alternating between the light and dark blue.
> 
> Could we also add this sign in prompt to the share an email feature on the `Manage List` page. What do you think?

@rachelspencer Thanks for the feedback! I've added these changes.

**Review by sillytsundere — APPROVED** [review]
Hey Jose! Everything looks great and works well! 

My one comment is, could we rework the css somehow? or for the things other than the dialogue box and buttons use the theming from our index.css style sheet. I am asking this because when I open the app the background of the main section is white. But the Navbar and the header still share the previous background color set to the dark theme we had previously. I'll attach a picture. Is there a way we can have themes with Radix? I wasn't able to quite see why this was happening. 
Screenshot 2024-03-28 at 3 23 07 PM
 Other than the styling though the functionality is great! Good job! :3

**Comment by jaguilar89** [comment]
> Hey Jose! Everything looks great and works well!
> 
> My one comment is, could we rework the css somehow? or for the things other than the dialogue box and buttons use the theming from our index.css style sheet. I am asking this because when I open the app the background of the main section is white. But the Navbar and the header still share the previous background color set to the dark theme we had previously. I'll attach a picture. Is there a way we can have themes with Radix? I wasn't able to quite see why this was happening.

@sillytsundere Thx for the feedback! I'll see if I can work this out. I didn't wanna step too far outside the scope of this issue so I tried to keep CSS changes to a minimum.

**Review by trushmi — APPROVED** [review]
Great work tackling this issue! Everything worked on my machine as expected when I was testing it. Speaking about Theme, I have noticed the same issue as @sillytsundere mentioned before. Let me know if you need help resolving this issue, or we can discuss and try to find the best approach during our regular meetings

**Pull request merged**
